### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by knutztar** [cakephp/cakephp-codesniffer#289]
Version: 4.0.1
Running phpcs on one of my files renders the following error: 

```
An error occurred during processing; checking has been aborted. The error message was: Uninitialized string offset: 0 in ../cakephp-codesniffer/CakePHP/Sniffs/Commenting/FunctionCommentSniff.php on line 275 (Internal.Exception)
```

Running phpcbf on the same file crashes with output:
```
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Uninitialized string offset: 0 in .../vendor/cakephp/cakephp-codesniffer/CakePHP/Sniffs/Commenting/FunctionCommentSniff.php on line 275 in .../vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 .../vendor/cakephp/cakephp-codesniffer/CakePHP/Sniffs/Commenting/FunctionCommentSniff.php(275): PHP_CodeSniffer\Runner->handleErrors(8, 'Uninitialized s...', '/path/...', 275, Array)
#1 .../vendor/squizlabs/php_codesniffer/src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php(98): CakePHP\Sniffs\Commenting\FunctionCommentSniff->processThrows(Object(PHP_CodeSniffer\Files\LocalFile), 332, 295)
#2 .../vendor/squizlabs/php_codesniffer/src/Files/File.php(496): PHP_CodeSniffer\Standards\PEAR\Sniffs\Commenting\FunctionCommentSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 332)
#3 .../vendor/squiz in .../vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
```

**Comment by othercorey** [comment]
Do you know which file? Does it have any @throw tags in it?

**Comment by knutztar** [comment]
Yes, I've found the issue. 

```
    /**
     * View method
     *
     * @throws \App\Controller\NotFoundException
     * @param string $id
     * @return void
     */
```

The issue appears only when `@throws \App\Controller\NotFoundException ` with a **whitespace** after NotFoundException and no comment is present. Removing the whitespace manually or entering a comment works as a work around.
